//
//  RocketDetailWorker.swift
//  SpaceX
//
//  Created by Canberk Bibican on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RocketDetailWorker{
    
    var rocketStore: RocketStoreProtocol

    init(rocketStore: RocketStoreProtocol) {
        self.rocketStore = rocketStore
    }

    func getRocketDetail(request: RocketDetail.GetRocketDetail.Request, completion: @escaping ((_ response: RocketDetailResponseModel?, _ error: Error?) -> Void)) {
        self.rocketStore.getRocketDetail(request: request) { result in
            switch result {
            case .success(let rocket):
                completion(rocket, nil)
            case .failure(let error):
                completion(nil, error)
            }
        }
    }
}
