//
//  RocketDetailPresenter.swift
//  SpaceX
//
//  Created by Canberk Bibican on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketDetailPresentationLogic {
    func presentRocket(response: RocketDetail.GetRocketDetail.Response)
    func presentRocketError(error: Error)
    func dataPass(data: Rockets.GetRocketList.RocketDetailPassData?)
}

class RocketDetailPresenter: RocketDetailPresentationLogic {
    weak var viewController: RocketDetailDisplayLogic?

    func presentRocket(response: RocketDetail.GetRocketDetail.Response) {
        let rocket = response.rocket
        let displayedRocket: RocketDetail.GetRocketDetail.ViewModel.DisplayedRocket = RocketDetail.GetRocketDetail.ViewModel.DisplayedRocket(rocketId: rocket.rocketID, rocketName: rocket.rocketName, rocketDescription: rocket.rocketDescription, rocketImage: rocket.flickrImages?.first ?? "https://unsplash.com/photos/woWf_VJ7dNs")

        let viewModel = RocketDetail.GetRocketDetail.ViewModel(displayedRocket: displayedRocket)
        viewController?.displayGetRocket(viewModel: viewModel)
    }

    func presentRocketError(error: Error) {
        viewController?.displayRocketError(error: error)
    }
    
    func dataPass(data: Rockets.GetRocketList.RocketDetailPassData?) {
        viewController?.passingData(data: data)
    }

}
