//
//  RocketDetailInteractor.swift
//  SpaceX
//
//  Created by Canberk Bibican on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketDetailBusinessLogic {
    func getRocket(request: RocketDetail.GetRocketDetail.Request)
    func getPassingData()
}

protocol RocketDetailDataStore {
    var passingData: Rockets.GetRocketList.RocketDetailPassData? { get set }
    var rocket: RocketDetailResponseModel? { get }
}

class RocketDetailInteractor: RocketDetailBusinessLogic, RocketDetailDataStore {

    var passingData: Rockets.GetRocketList.RocketDetailPassData?
    var rocket: RocketDetailResponseModel?
    var presenter: RocketDetailPresentationLogic?
    var worker = RocketDetailWorker(rocketStore: RocketsService())

    // MARK: Do something

    func getPassingData(){
        presenter?.dataPass(data: passingData)
    }

    func getRocket(request: RocketDetail.GetRocketDetail.Request) {
        worker.getRocketDetail(request: request) { rocket, error in
            if error != nil {
                self.presenter?.presentRocketError(error: error!)
            } else {
                self.rocket = rocket
                let response = RocketDetail.GetRocketDetail.Response(rocket: rocket!)
                self.presenter?.presentRocket(response: response)
            }
        }
    }
}
