//
//  RocketDetailModels.swift
//  SpaceX
//
//  Created by Canberk Bibican on 17.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RocketDetail {
    // MARK: Use cases

    enum GetRocketDetail {
        struct Request {
            let rocketId: String?
        }
        struct Response {
            var rocket: RocketDetailResponseModel
        }

        struct ViewModel {
            struct DisplayedRocket {
                var rocketId: String?
                var rocketName: String?
                var rocketDescription: String?
                var rocketImage: String?
            }
            var displayedRocket: DisplayedRocket
        }
    }
}
