//
//  RocketsModels.swift
//  SpaceX
//
//  Created by Canberk Bibican on 16.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Rockets {

    enum GetRocketList {

        struct Request {
            
        }

        struct Response {
            var rockets: [RocketsResponseModel]
        }

        struct ViewModel {
            struct DisplayedRocket {
                var rocketId: String?
                var rocketName: String?
                var rocketDescription: String?
                var rocketImage: String?
            }
            var displayedRockets: [DisplayedRocket]
        }
    }
}
