//
//  RocketsRouter.swift
//  SpaceX
//
//  Created by Canberk Bibican on 16.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RocketsRoutingLogic {
    func routeToRocketDetail(segue: UIStoryboardSegue?)
}

protocol RocketsDataPassing {
    var dataStore: RocketsDataStore? { get }
}

class RocketsRouter: NSObject, RocketsRoutingLogic, RocketsDataPassing {
    weak var viewController: RocketsViewController?
    var dataStore: RocketsDataStore?

    // MARK: Routing

    func routeToRocketDetail(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! RocketDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToRocketDetail(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "RocketDetailViewController") as! RocketDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToRocketDetail(source: dataStore!, destination: &destinationDS)
            navigateToRocketDetail(source: viewController!, destination: destinationVC)
        }
    }

    /// MARK: Navigation

    func navigateToRocketDetail(source: RocketsViewController, destination: RocketDetailViewController) {
        source.show(destination, sender: nil)
    }

    /// MARK: Passing data

    func passDataToRocketDetail(source: RocketsDataStore, destination: inout RocketDetailDataStore) {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        let selectedItem = source.rockets![selectedRow!]
        let passingData = Rockets.GetRocketList.RocketDetailPassData(rocketID: selectedItem.rocketID ?? "", rocketName: selectedItem.rocketName ?? "")
        destination.passingData = passingData
    }
}
