//
//  RocketsInteractor.swift
//  SpaceX
//
//  Created by Canberk Bibican on 16.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketsBusinessLogic {
    func getRocketList(request: Rockets.GetRocketList.Request)
}

protocol RocketsDataStore {
    var rockets: [RocketsResponseModel]? { get }
}

class RocketsInteractor: RocketsBusinessLogic, RocketsDataStore {
    var rockets: [RocketsResponseModel]?

    var presenter: RocketsPresentationLogic?
    var worker = RocketsWorker(rocketStore: RocketsService())

    // MARK: Fetch Rockets
    func getRocketList(request: Rockets.GetRocketList.Request) {
        worker.getRocketList(completion: { (rockets, error) in
            if error != nil {
                self.presenter?.presentRocketError(error: error!)
                //TODO: Bu kısımda hata mesajını ekranda göstermek için Clean Swift döngüsü çalıştırabilirsiniz.
            } else {
                self.rockets = rockets
                let response = Rockets.GetRocketList.Response(rockets: rockets)
                self.presenter?.presentRockets(response: response)
            }
        })
    }
}
