//
//  RocketsWorker.swift
//  SpaceX
//
//  Created by Canberk Bibican on 16.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//Worker -> Servise çağrı atar ve gelen responsu protocolunu kullanan classlara iletir. (Presenter)

class RocketsWorker {

    var rocketStore: RocketStoreProtocol

    init(rocketStore: RocketStoreProtocol) {
        self.rocketStore = rocketStore
    }

    func getRocketList(completion: @escaping ((_ response: [RocketsResponseModel], _ error: Error?) -> Void)) {
        self.rocketStore.getRocketList { result in
            switch result {
            case .success(let rockets):
                completion(rockets, nil)
                print(rockets)
            case .failure(let error):
                completion([], error)
            }
        }
    }
}
