//
//  RocketsPresenter.swift
//  SpaceX
//
//  Created by Canberk Bibican on 16.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// Presenter -> Response'u alır viewModele dönüştürüp viewController'a paslar

protocol RocketsPresentationLogic {
    func presentRockets(response: Rockets.GetRocketList.Response)
    func presentRocketError(error: Error)
}

class RocketsPresenter: RocketsPresentationLogic {

    weak var viewController: RocketsDisplayLogic?

    func presentRockets(response: Rockets.GetRocketList.Response) {

        var displayedRockets: [Rockets.GetRocketList.ViewModel.DisplayedRocket] = []

        for rocket in response.rockets {
            let displayedRocket = Rockets.GetRocketList.ViewModel.DisplayedRocket(rocketId: rocket.rocketID, rocketName: rocket.rocketName, rocketDescription: rocket.rocketDescription, rocketImage: rocket.flickrImages?.first ?? "https://unsplash.com/photos/woWf_VJ7dNs")
            displayedRockets.append(displayedRocket)
        }
        let viewModel = Rockets.GetRocketList.ViewModel(displayedRockets: displayedRockets)
        viewController?.displayGetRocketList(viewModel: viewModel)
    }
    
    func presentRocketError(error: Error) {
        viewController?.displayRocketError(error: error)
    }
    
}
